In [1]:
import pandas as pd

pd.options.display.max_rows = 999

columns_1 = ['leave','value_1']
columns_2 = ['leave','value_2']

In [2]:
df1 = pd.read_csv('leave_values_20200515_smoothed.csv', header=None, names=columns_1).set_index('leave')

In [3]:
# df2 = pd.read_csv('leave_values_20191208.csv', header=None)
# df2 = pd.read_csv('leave_values_20191208.csv', header=None)
# df2 = pd.read_csv('leave_values_20200423_filled_nulls.csv', header=None, names=columns_2).set_index('leave')
df2 = pd.read_csv('leave_values_20200512_smoothed.csv', header=None, names=columns_2).set_index('leave')

In [4]:
df = pd.concat([df1,df2],axis=1)
df = df.reset_index()

In [5]:
df['delta'] = df['value_1']-df['value_2']
df['length'] = df['leave'].apply(lambda x: len(x))
df['vowels'] = df['leave'].apply(lambda x: sum([y in 'AEIOU' for y in x]))
df['consonants'] = df['length']-df['vowels']
df['has_a_blank'] = df['leave'].apply(lambda x: sum([y=='?' for y in x])>0)
df['has_two_blanks'] = df['leave'].apply(lambda x: sum([y=='?' for y in x])==2)

In [9]:
df.loc[df['length']==1].sort_values('delta')

,leave,value_1,value_2,delta,length,vowels,consonants,has_a_blank,has_two_blanks
17,Q,-7.261103,-6.310262,-0.950841,1,0,1,False,False
22,V,-6.311102,-5.755407,-0.555695,1,0,1,False,False
10,J,-3.507410,-2.966566,-0.540844,1,0,1,False,False
24,X,1.475522,1.936762,-0.461239,1,0,1,False,False
26,Z,3.929423,4.376830,-0.447407,1,0,1,False,False
21,U,-4.561214,-4.150599,-0.410614,1,1,0,False,False
23,W,-4.650212,-4.258410,-0.391801,1,0,1,False,False
6,F,-3.323056,-2.932341,-0.390716,1,0,1,False,False
2,B,-3.013219,-2.625032,-0.388187,1,0,1,False,False
11,K,-1.377316,-1.019575,-0.357741,1,0,1,False,False
7,G,-3.038880,-2.695502,-0.343378,1,0,1,False,False
25,Y,-1.795780,-1.479030,-0.316750,1,0,1,False,False
12,L,-0.510396,-0.195833,-0.314563,1,0,1,False,False
4,D,0.271970,0.532724,-0.260754,1,0,1,False,False
15,O,-1.410013,-1.184638,-0.225374,1,1,0,False,False
13,M,0.208370,0.427981,-0.219611,1,0,1,False,False
8,H,0.636673,0.843866,-0.207193,1,0,1,False,False
16,P,-0.506486,-0.330358,-0.176128,1,0,1,False,False
14,N,0.914641,1.054765,-0.140124,1,0,1,False,False
1,A,1.282753,1.371000,-0.088247,1,1,0,False,False
5,E,2.361061,2.429838,-0.068777,1,1,0,False,False
3,C,0.750034,0.810967,-0.060932,1,0,1,False,False
9,I,0.465353,0.513574,-0.048221,1,1,0,False,False
20,T,1.138034,1.130796,0.007238,1,0,1,False,False
18,R,1.961796,1.916446,0.045350,1,0,1,False,False
19,S,7.776772,7.528380,0.248393,1,0,1,False,False
0,?,25.198703,24.078203,1.120500,1,0,1,True,False

#### Remaining ideas
1. RMS error by leave length
2. Heatmap of error by vowel-consonant ratio

In [17]:
x_tile_df = {i: df.loc[df['length']==i][['leave','value_1','value_2','delta']].sort_values('delta') for i in range(1,7)}

In [18]:
one_tile_df = x_tile_df[1].rename(columns={'value_1':'macondo_0508','value_2':'quackle'})

In [19]:
two_tile_df = x_tile_df[2].rename(columns={'value_1':'macondo_0508','value_2':'quackle'})

In [14]:
one_tile_df.to_csv('comp_1tileleaves_0508_quackle.csv', index=False)

In [15]:
two_tile_df.to_csv('comp_2tileleaves_0508_quackle.csv', index=False)

In [25]:
x_tile_df[6]

         leave     value_1  value_2       delta
894238  ?MPPYZ  -13.209689  24.3984  -37.608089
704275  ??FGGG   -9.321189  27.1680  -36.489189
876321  ?LLLLV  -34.996129   0.6875  -35.683629
560349  ??DDVV  -16.429689  18.8164  -35.246089
532265  ?CLLLL  -29.270104   5.4375  -34.707604
...        ...         ...      ...         ...
886010  ??LPQX  121.631644  18.6797  102.951944
887144  ??LQXY  134.498811  21.5391  112.959711
879005  ??LLQX  132.487597  17.5586  114.928997
618171  ??DLQX  228.663267  16.8477  211.815567
559834  ??DDQX  230.742978  14.5391  216.203878

[737311 rows x 4 columns]